package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Light Palette - Professional Polish
val PolishPrimaryLight = Color(0xFF386A20)
val PolishOnPrimaryLight = Color(0xFFFFFFFF)
val PolishPrimaryContainerLight = Color(0xFFD3EABC)
val PolishOnPrimaryContainerLight = Color(0xFF102003)
val PolishSecondaryLight = Color(0xFF536348)
val PolishOnSecondaryLight = Color(0xFFFFFFFF)
val PolishSecondaryContainerLight = Color(0xFFEEF1E4)
val PolishOnSecondaryContainerLight = Color(0xFF1B1F17)
val PolishTertiaryLight = Color(0xFF39656B)
val PolishOnTertiaryLight = Color(0xFFFFFFFF)
val PolishTertiaryContainerLight = Color(0xFFBCEBF2)
val PolishOnTertiaryContainerLight = Color(0xFF001F23)
val PolishBackgroundLight = Color(0xFFFDFDF5)
val PolishOnBackgroundLight = Color(0xFF1A1C18)
val PolishSurfaceLight = Color(0xFFFDFDF5)
val PolishOnSurfaceLight = Color(0xFF1A1C18)
val PolishSurfaceVariantLight = Color(0xFFEEF1E4)
val PolishOnSurfaceVariantLight = Color(0xFF43493E)
val PolishOutlineLight = Color(0xFF73796E)
val PolishOutlineVariantLight = Color(0xFFE1E4D5)

// Dark Palette - Professional Polish Dark
val PolishPrimaryDark = Color(0xFF98D775)
val PolishOnPrimaryDark = Color(0xFF0F3900)
val PolishPrimaryContainerDark = Color(0xFF20510A)
val PolishOnPrimaryContainerDark = Color(0xFFD3EABC)
val PolishSecondaryDark = Color(0xFFBCCBB0)
val PolishOnSecondaryDark = Color(0xFF273421)
val PolishSecondaryContainerDark = Color(0xFF3B4A33)
val PolishOnSecondaryContainerDark = Color(0xFFEEF1E4)
val PolishTertiaryDark = Color(0xFFA0CFD6)
val PolishOnTertiaryDark = Color(0xFF00363C)
val PolishTertiaryContainerDark = Color(0xFF1F4D53)
val PolishOnTertiaryContainerDark = Color(0xFFBCEBF2)
val PolishBackgroundDark = Color(0xFF1A1C18)
val PolishOnBackgroundDark = Color(0xFFE3E3DC)
val PolishSurfaceDark = Color(0xFF1A1C18)
val PolishOnSurfaceDark = Color(0xFFE3E3DC)
val PolishSurfaceVariantDark = Color(0xFF43493E)
val PolishOnSurfaceVariantDark = Color(0xFFC3C8BB)
val PolishOutlineDark = Color(0xFF8D9287)
val PolishOutlineVariantDark = Color(0xFF43493E)
